name: Java CI

on:
  # Trigger bei jedem Push und Pull Request
  push:
    branches:
      - '*'    # Alle Branches
  pull_request:
    branches:
      - '*'    # Alle Branches

jobs:
  # Job 1: Tests ausführen
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Install dependencies
        run: mvn install

      - name: Run tests
        run: mvn test